service: serverless-example
app: serverless-product-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: app.ts # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-http